pipeline {
    agent any
    environment {
        DOCKER_IMAGE = "node-app"
        DOCKER_TAG = "v1"
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/Shivappapadennavar/docker.git'
            }
        }

        stage('Extract Node App') {
            steps {
                sh 'unzip -o node-app.zip -d node'
            }
        }

        stage('Install Node Modules') {
            steps {
                dir('node/node-app') {
                    sh 'npm install'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('node/node-app') {
                    sh 'docker build -t $DOCKER_IMAGE:$DOCKER_TAG .'
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                sh '''
                docker stop node_container || true
                docker rm node_container || true
                docker run -d --name node_container -p 3000:3000 $DOCKER_IMAGE:$DOCKER_TAG
                '''
            }
        }
    }
}
